name: release
on:
  push:
    branches:
      - main
      - feat/electron

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build
          working-directory: webui
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: List files
        run: ls -ltr release/*
        working-directory: webui
