name: release desktop app for mac arm64
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build
          working-directory: webui
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: List files
        run: ls -ltr release/*
        working-directory: webui
      - name: Upload assets to Cloudflare R2
        run: |
          mkdir -p r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cp fluentci-studio_*_arm64.dmg r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cp fluentci-studio_*_arm64.zip r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cd r2 && fluentci run --wasm r2-sync upload --endpoint-url https://$ACCOUNT_ID.r2.cloudflarestorage.com s3://assets
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_ID: fe5b1e2ce9f94f4c0415ab94ce402012
      - name: Upload release assets
        run: |
          for ext in dmg zip; do
            export FILE=fluentci-studio_*_arm64.$ext
            fluentci run --wasm github release_upload $TAG $FILE
          done
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
