name: release for mac
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-12
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build
          working-directory: webui
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: build
        run: |
          fluentci run --wasm rust target_add ${{ matrix.target }}
          fluentci run --wasm rust build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/fluentci-studio .
          tar czvf fluentci-studio-${{ matrix.target }}.tar.gz fluentci-studio
          shasum -a 256 fluentci-studio-${{ matrix.target }}.tar.gz > fluentci-studio-${{ matrix.target }}.tar.gz.sha256
          ls -ltr
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
