name: release desktop app for linux
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build
          working-directory: webui
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: List files
        run: ls -ltr release/*
        working-directory: webui
      - name: Upload assets to Cloudflare R2
        run: |
          mkdir -p r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          shasum -a 256 fluentci-studio_${{ env.RELEASE_VERSION }}.AppImage > fluentci-studio_${{ env.RELEASE_VERSION }}.AppImage.sha256
          sha256sum fluentci-studio_${{ env.RELEASE_VERSION }}.tar.gz > fluentci-studio_${{ env.RELEASE_VERSION }}.tar.gz.sha256
          cp fluentci-studio_${{ env.RELEASE_VERSION }}.AppImage r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cp fluentci-studio_${{ env.RELEASE_VERSION }}.AppImage.sha256 r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cp fluentci-studio_${{ env.RELEASE_VERSION }}.tar.gz r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cp fluentci-studio_${{ env.RELEASE_VERSION }}.tar.gz.sha256 r2/fluentci-studio/${{ env.RELEASE_VERSION }}
          cd r2 && fluentci run --wasm r2-sync upload --endpoint-url https://$ACCOUNT_ID.r2.cloudflarestorage.com s3://assets
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_ID: fe5b1e2ce9f94f4c0415ab94ce402012
        working-directory: webui/release/${{ env.RELEASE_VERSION }}
      - name: Upload release assets
        run: |
          for ext in tar.gz AppImage tar.gz.sha256 AppImage.sha256; do
            export FILE=fluentci-studio_${{ env.RELEASE_VERSION }}.$ext
            fluentci run --wasm github release_upload $TAG $FILE
          done
        env:
          TAG: ${{ env.RELEASE_VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        working-directory: webui/release/${{ env.RELEASE_VERSION }}
