name: release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v2
      - name: Setup Fluent CI and build webui
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true
          pipeline: bun
          args: |
            run build
          working-directory: webui
      - name: Set RUSTFLAGS
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          echo "RUSTFLAGS=-C linker=aarch64-linux-gnu-gcc -L/usr/aarch64-linux-gnu/lib" >> $GITHUB_ENV
      - name: build
        run: |
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu libc6-arm64-cross libc6-dev-arm64-cross pkg-config
          fluentci run --wasm rust target_add ${{ matrix.target }}
          fluentci run --wasm rust build --release --target ${{ matrix.target }}
          cp target/${{ matrix.target }}/release/fluentci-studio .
          tar czvf fluentci-studio-${{ matrix.target }}.tar.gz fluentci-studio
          shasum -a 256 fluentci-studio-${{ matrix.target }}.tar.gz > fluentci-studio-${{ matrix.target }}.tar.gz.sha256
          ls -ltr
